"""Harvest LoRA metadata example prompts into a checked-in JS data module.

Reads <lora-dir>/*.metadata.json (inference.example_prompts + trigger +
recommended strength), emits app/static/js/ref-music-prompts.js exporting
MUSIC_PROMPT_EXAMPLES. Re-run when the folder grows; diff the output.

Usage: python3 tools/gen_music_prompt_bank.py [lora-dir] [out-js]
Defaults: /home/m/snc/cod/testLamaEraser/ACE-Step-LoRAs/acestep_loras_flat
"""
import json
import sys
from pathlib import Path

LORA_DIR = Path(sys.argv[1] if len(sys.argv) > 1 else
                "/home/m/snc/cod/testLamaEraser/ACE-Step-LoRAs/acestep_loras_flat")
OUT = Path(sys.argv[2] if len(sys.argv) > 2 else
           Path(__file__).resolve().parents[1] / "app/static/js/ref-music-prompts.js")


def main():
    seen = set()
    examples = []
    for meta_path in sorted(LORA_DIR.glob("*.metadata.json")):
        try:
            d = json.load(open(meta_path))
        except Exception:
            continue
        inf = d.get("inference", {})
        trigger = inf.get("primary_trigger_word", "")
        for ex in inf.get("example_prompts", []):
            cap = (ex.get("caption") or "").strip()
            if not cap or cap.lower() in seen:
                continue
            seen.add(cap.lower())
            examples.append({
                "caption": cap,
                "bpm": ex.get("bpm"),
                "key": ex.get("key"),
                "trigger": trigger,
                "source": meta_path.stem,
            })
    lines = ["// AUTO-GENERATED by tools/gen_music_prompt_bank.py — do not hand-edit.",
             f"// {len(examples)} examples from {LORA_DIR}",
             "export const MUSIC_PROMPT_EXAMPLES = "]
    lines.append(json.dumps(examples, indent=1) + ";")
    lines.append("")
    OUT.write_text("\n".join(lines))
    print(f"wrote {len(examples)} examples -> {OUT}")


if __name__ == "__main__":
    main()
