"""
Unified Speed & Time — target-length or target-multiplier, optional RIFE.

The operation is anchored by a single source of truth:
  Target Mode = Length  →  user sets the exact output duration
  Target Mode = Multiplier  →  user sets the exact speed factor
  Output FPS  = Match source (default) or a custom rate (`target_fps`).

Deterministic math (UI readout and backend share this model):

  1. Output FPS (F) is the input video's native FPS unless `target_fps` is set.
     FFmpeg drops/duplicates frames during the encode to hold the rate.
  2. Final Duration (T)  = Input Duration / Exact Speed Multiplier (S).
  3. Target Total Frames (R) = T × F  — the exact frame count on disk.
  4. RIFE ON (slow-mo): Required Multiplier (M) = smallest valid RIFE
     step (2, 4, 8, …) with Generated Frames (G = N×M) ≥ R, i.e. M ≥ (F/src_fps)/S.
  5. Extra frames (G − R) are generated by RIFE then dropped by the
     conforming encode to hit T exactly at F fps.
  6. Snap (multiplier mode only): M = nearest valid step to (F/src_fps)/S,
     then lock S = (F/src_fps)/M so G == R exactly (zero extra frames).
  7. Free mode overage (`keep_extra`): trim = drop G−R; fps = encode all at
     G/T inside duration T; length = encode all at F, duration → G/F
     (effective speed = D / (G/F)). `fps` requires target_fps=None (no
     silent override of a pinned output FPS).

Fast path (no RIFE): ffmpeg `setpts` + `fps=F` re-times in one pass.
RIFE path: dump → `app.filters.rife.run_rife_directory` → thin G→R → encode @ F.
"""
from __future__ import annotations

import math
import uuid
from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel, Field, model_validator

from ..frame_range import end_frame_field, start_frame_field
from ..contract import OperationResult, OperationSpec, register
from ..pathutil import finalize_output_path
from ..shell import run_command

RifeModel = Literal["rife-v4.6", "rife-v4", "rife-v2.4", "rife-v2.3"]
AudioMode = Literal["preserve", "pitch", "drop"]
TargetMode = Literal["length", "multiplier"]
KeepExtra = Literal["trim", "fps", "length"]
VIDEO_EXTS = {".mp4", ".m4v", ".mov", ".mkv", ".webm", ".avi"}


class SpeedChangeParams(BaseModel):
    input_path: str = Field(..., description="Source video path")
    output_path: str | None = Field(None, description="Output path; auto-named if omitted")
    target_mode: TargetMode = Field(
        "multiplier",
        description="What drives the math: 'length' = exact output duration, "
                    "'multiplier' = exact speed factor",
    )
    target_length: float | None = Field(
        None, gt=0.1, le=3600,
        description="Target output duration in seconds (target_mode='length')",
    )
    speed: float = Field(
        1.0, ge=0.1, le=10.0,
        description="Exact speed multiplier: 2 = 2× faster, 0.5 = half speed",
    )
    use_rife: bool = Field(
        False, description="Interpolate frames with RIFE before the conforming encode",
    )
    rife_snap: bool = Field(
        False, description="Multiplier mode only: snap speed to (target_fps/src_fps)/M so no extra frames are generated",
    )
    target_fps: float | None = Field(
        None, ge=1, le=240,
        description="Optional FPS override; blank = lock to input native FPS",
    )
    keep_extra: KeepExtra = Field(
        "trim",
        description="Free mode only — what to do with generated frames that exceed "
                    "the target: trim=drop extras to hit the exact plan, fps=encode "
                    "all at a raised rate inside the same duration (requires "
                    "target_fps=null), length=encode all at the output rate and "
                    "stretch the duration",
    )
    audio_mode: AudioMode = Field(
        "preserve",
        description="preserve=atempo pitch-lock, pitch=chipmunk/deep, drop=no audio",
    )
    model: RifeModel = Field("rife-v4.6", description="RIFE model")
    tta: bool = Field(False, description="RIFE spatial TTA")
    uhd: bool = Field(False, description="RIFE UHD mode")
    start_frame: int = start_frame_field()
    end_frame: int = end_frame_field()
    dry_run: bool = Field(False, description="Plan only")

    @model_validator(mode="after")
    def _keep_extra_needs_free_fps(self) -> "SpeedChangeParams":
        # The FPS branch would have to override a pinned output FPS — the one
        # "silent takeover" this operation forbids.
        if self.keep_extra == "fps" and self.target_fps is not None:
            raise ValueError(
                "keep_extra='fps' cannot be combined with a pinned target_fps"
            )
        return self


def _valid_rife_multipliers() -> list[int]:
    """Valid RIFE density steps: powers of two from 2 up to 128."""
    return [2 ** i for i in range(1, 8)]


def _next_rife_multiplier(target_m: float) -> int:
    """Smallest valid RIFE step (2,4,8,…) >= max(2, target_m)."""
    floor = max(2, target_m)
    return 2 ** max(1, int(math.ceil(math.log2(floor))))


def _snap_rife_multiplier(target_m: float) -> int:
    """Nearest valid RIFE step to target_m (Snap mode lock)."""
    best = 2
    best_dist = abs(math.log2(2.0 / target_m)) if target_m > 0 else 1e9
    for m in _valid_rife_multipliers():
        dist = abs(math.log2(m / target_m))
        if dist < best_dist:
            best_dist, best = dist, m
    return best


def _build_atempo_chain(speed: float) -> str:
    """Chain atempo filters — each stage is in [0.5, 100]."""
    parts: list[str] = []
    remaining = float(speed)
    while remaining < 0.5 - 1e-9:
        parts.append("atempo=0.5")
        remaining /= 0.5
    while remaining > 100.0 + 1e-9:
        parts.append("atempo=100.0")
        remaining /= 100.0
    if abs(remaining - 1.0) > 1e-3:
        parts.append(f"atempo={remaining:.6f}")
    return ",".join(parts) if parts else "anull"


def resolve_speed_plan(
    *,
    src_duration: float,
    src_fps: float,
    src_frames: int,
    target_mode: TargetMode = "multiplier",
    target_length: float | None = None,
    speed: float = 1.0,
    use_rife: bool = False,
    rife_snap: bool = False,
    target_fps: float | None = None,
    keep_extra: str = "trim",
) -> dict[str, Any]:
    """Return the deterministic plan for the unified speed operation.

    Output FPS F is the source rate by default, or an explicit `target_fps`.
    Model: T = D/S, R = T × F (exact frames on disk). With RIFE the required
    step is the smallest valid M with G = N×M >= R, i.e. M >= (F/src_fps)/S.
    Snap (multiplier mode only) pins M to the nearest valid step and locks
    S = (F/src_fps)/M so G == R exactly (zero extra frames).

    `keep_extra` (Free mode only, when G > R):
      trim   — drop G − R frames; everything matches the chosen values exactly
      fps    — keep all G frames inside duration T, final FPS becomes G/T
      length — keep all G frames at F, duration stretches to G/F (effective
               speed = D/(G/F)). Requires target_fps is None (fps stays yours).

    Mirrors the UI readout (resolveUsPlan in tabs/speedchange.js).
    """
    F_src = float(src_fps) if src_fps and src_fps > 0 else 30.0
    F = float(target_fps) if target_fps and target_fps > 0 else F_src
    if F <= 0:
        F = 30.0
    ratio = (F / F_src) if F_src > 0 else 1.0
    N = max(int(src_frames), 0)
    D = max(float(src_duration), 0.0)
    if N <= 0 or D <= 0:
        D = N / F_src if N > 0 else D

    # Exact multiplier from target mode
    if target_mode == "length":
        T = max(0.1, float(target_length or (D / speed if speed > 0 else D)))
        S = (D / T) if T > 0 and D > 0 else speed
    else:
        S = float(speed)
        T = (D / S) if S > 0 else D

    S = min(10.0, max(0.1, S))
    T = max(0.1, T)

    # Snap: lock S so G == R exactly (multiplier mode only)
    M: int | None = None
    G = 0
    snapped = False
    if use_rife:
        if rife_snap and target_mode == "multiplier":
            K = (ratio / S) if S > 0 else 2.0
            M = _snap_rife_multiplier(K)
            S = (ratio / M) if M > 0 else S
            T = (D / S) if S > 0 else D
            snapped = True
        K = (ratio / S) if S > 0 else 2.0
        M = _next_rife_multiplier(K)
        G = N * M

    R = T * F  # exact frames on disk
    extra = max(0.0, G - R) if use_rife else 0.0
    kept_mode: str | None = None
    if use_rife and extra > 0.5 and keep_extra != "trim":
        # Keep the Change — spend the overage instead of dropping it.
        if keep_extra == "fps":
            F = G / T if T > 0 else F
            R = float(G)
            extra = 0.0
        elif keep_extra == "length":
            T = G / F if F > 0 else T
            S = (D / T) if T > 0 else S
            R = float(G)
            extra = 0.0
        kept_mode = keep_extra

    return {
        "src_duration": D,
        "src_fps": round(F_src, 3),
        "src_frames": N,
        "target_mode": target_mode,
        "exact_speed": round(S, 6),
        "final_duration": round(T, 4),
        "final_fps": round(F, 3),
        "target_frames": round(R, 2),
        "rife_multiplier": M if use_rife else None,
        "generated_frames": G if use_rife else None,
        "extra_frames": round(extra, 2) if use_rife else None,
        "kept_mode": kept_mode,
        "snapped": snapped,
    }


async def speedchange(p: SpeedChangeParams) -> OperationResult:
    from .. import job_control
    from ..job_workspace import JobWorkspace
    from ..video_pipeline import probe, dump, encode, cleanup
    from ..filters.rife import run_rife_directory, resolve_rife_bin

    inp = Path(p.input_path).expanduser().resolve()
    if not inp.is_file():
        return OperationResult(
            ok=False, operation="speedchange",
            error=f"Input not found: {inp}", dry_run=p.dry_run,
        )

    try:
        info = await probe(str(inp))
    except Exception as e:
        return OperationResult(
            ok=False, operation="speedchange", error=f"probe failed: {e}",
            dry_run=p.dry_run,
        )

    src_fps = float(info.get("fps") or 24.0)
    n_full = int(info.get("frame_count") or 0)
    n = n_full
    if p.start_frame > 1 or (p.end_frame < 999999 and p.end_frame > 0):
        end = p.end_frame if p.end_frame < 999999 else n_full
        start = max(1, p.start_frame)
        n = max(0, end - start + 1)
    if n <= 0:
        n = n_full

    src_dur = (n / src_fps) if src_fps > 0 else float(info.get("duration") or 0)
    plan = resolve_speed_plan(
        src_duration=src_dur,
        src_fps=src_fps,
        src_frames=n,
        target_mode=p.target_mode,
        target_length=p.target_length,
        speed=p.speed,
        use_rife=p.use_rife,
        rife_snap=p.rife_snap,
        target_fps=p.target_fps,
        keep_extra=p.keep_extra,
    )
    S = float(plan["exact_speed"])
    T = float(plan["final_duration"])
    F = float(plan["final_fps"])
    R = float(plan["target_frames"])
    M = int(plan["rife_multiplier"] or 1)

    out = finalize_output_path(
        p.output_path,
        source=inp,
        default_suffix=f"_speed{S:g}x".replace(".", "p"),
        default_ext=".mp4",
        allowed_exts=VIDEO_EXTS,
    )

    summary = (
        f"speedchange {inp.name} {S:g}× → {T:.3g}s @ {F:g}fps "
        f"audio={p.audio_mode} rife={p.use_rife}"
        + (f"×{M}" if p.use_rife else " fast")
    )
    plan_line = (
        f"final: {plan['target_frames']:g} frames (of {plan['generated_frames'] or plan['src_frames']} "
        f"{'generated' if p.use_rife else 'available'})"
    )

    if p.dry_run:
        lines = [summary, plan_line]
        if p.use_rife:
            if plan["kept_mode"] == "trim" or plan["kept_mode"] is None:
                lines.append(
                    f"# dump → rife ×{M} ({plan['generated_frames']} frames) → "
                    f"thin to {R:g} → encode @ {F:g} fps"
                )
            else:
                lines.append(
                    f"# dump → rife ×{M} ({plan['generated_frames']} frames) → "
                    f"keep all → encode @ {F:g} fps ({plan['kept_mode']})"
                )
        else:
            lines.append(f"# ffmpeg -vf setpts={1.0/S:.6f}*PTS,fps={F:g} …")
        return OperationResult(
            ok=True, operation="speedchange", output_path=str(out),
            dry_run=True, command=summary, stdout="\n".join(lines), meta=plan,
        )

    logs = [summary, plan_line]
    job_control.report_progress(
        "speedchange start", phase="speed", current=0, total=1, unit="pass",
    )

    # ── Fast path: pure ffmpeg (drop/dup frames to hit T @ F) ───────────
    if not p.use_rife:
        vf = f"setpts={1.0 / S:.6f}*PTS,fps={F:.6g}"
        argv = [
            "ffmpeg", "-hide_banner", "-y",
            "-i", str(inp),
            "-vf", vf,
            "-c:v", "libx264", "-preset", "fast", "-crf", "18", "-pix_fmt", "yuv420p",
        ]
        has_audio = bool(info.get("has_audio"))
        if not has_audio or p.audio_mode == "drop":
            argv.append("-an")
        elif p.audio_mode == "preserve":
            argv.extend(["-af", _build_atempo_chain(S), "-c:a", "aac", "-b:a", "192k"])
        else:  # pitch
            argv.extend([
                "-af", f"asetpts={1.0 / S:.6f}*PTS",
                "-c:a", "aac", "-b:a", "192k",
            ])
        argv.append(str(out))
        job_control.report_progress("ffmpeg speed", phase="encode", current=0, total=1, unit="pass")
        code, stdout, stderr = await run_command(argv)
        if code != 0:
            return OperationResult(
                ok=False, operation="speedchange", error=(stderr or "ffmpeg failed")[-800:],
                dry_run=False, command=summary, stdout="\n".join(logs), stderr=stderr,
            )
        job_control.report_progress("encode done", phase="encode", current=1, total=1, unit="pass")
        logs.append(f"Output: {out}")
        return OperationResult(
            ok=True, operation="speedchange", output_path=str(out),
            dry_run=False, command=summary, stdout="\n".join(logs), meta=plan,
        )

    # ── RIFE path: dump → rife ×M → thin G→R → encode @ F ───────────────
    try:
        resolve_rife_bin()
    except RuntimeError as e:
        return OperationResult(
            ok=False, operation="speedchange", error=str(e), dry_run=False,
        )

    ws = JobWorkspace(uuid.uuid4().hex[:12], prefix="speedchange_")
    success = False
    try:
        job_control.report_progress("dump", phase="dump", current=0, total=1, unit="pass")
        dump_info = await dump(
            ws, str(inp), start_frame=p.start_frame, end_frame=p.end_frame,
        )
        in_n = int(dump_info["frame_count"])
        dump_fps = float(dump_info.get("fps") or src_fps)
        logs.append(f"dump: {in_n} frames @ {dump_fps:.4g} fps")

        job_control.report_progress(
            f"RIFE {M}x",
            phase="rife", current=0, total=in_n * M, unit="frames",
        )
        meta = await run_rife_directory(
            ws.frames_in, ws.frames_out,
            multiplier=M, model=p.model, tta=p.tta, uhd=p.uhd,
        )
        G = int(meta["frame_count_out"])
        logs.append(f"rife: {meta['frame_count_in']} → {G} frames")

        # Conform: keep exactly R of the G interpolated frames, renumber 0…
        R_int = int(round(R))
        R_int = max(1, min(G, R_int))
        frame_src = ws.frames_out
        if G > R_int:
            thin_dir = ws.root / "frames_conform"
            thin_dir.mkdir(parents=True, exist_ok=True)
            srcs = sorted(ws.frames_out.glob("frame_*.png"))
            for i in range(R_int):
                j = int(round(i * (G - 1) / max(R_int - 1, 1)))
                j = min(j, G - 1)
                (thin_dir / f"frame_{i:06d}.png").write_bytes(srcs[j].read_bytes())
            frame_src = thin_dir
            logs.append(f"conform: dropped {G - R_int} of {G} interpolated frames → {R_int} @ {F:g} fps")
        elif plan["kept_mode"] is not None:
            logs.append(f"keep_extra={plan['kept_mode']}: encoding all {G} frames @ {F:g} fps")

        # Audio: preserve stretches to T via atempo; pitch drops on the RIFE path
        mux = bool(ws.audio_path) and p.audio_mode != "drop"
        if mux and p.audio_mode == "preserve" and abs(S - 1.0) > 0.001:
            a_in = Path(ws.audio_path)
            a_out = ws.root / f"audio_speed{a_in.suffix}"
            af = _build_atempo_chain(S)
            acode, _, aerr = await run_command([
                "ffmpeg", "-hide_banner", "-y", "-i", str(a_in),
                "-af", af, str(a_out),
            ])
            if acode == 0 and a_out.is_file():
                ws.audio_path = a_out
                logs.append(f"audio: atempo chain ({S:g}×)")
            else:
                logs.append(f"audio atempo failed — dropping audio: {aerr[-200:]}")
                ws.audio_path = None
                mux = False
        elif mux and p.audio_mode == "pitch":
            logs.append("audio pitch mode with RIFE path: dropping audio (use fast path for pitch)")
            ws.audio_path = None
            mux = False

        job_control.report_progress("encode", phase="encode", current=0, total=1, unit="pass")
        result_path = await encode(
            ws, out, F, mux_audio=mux, crf=18, preset="fast",
            frame_source_dir=frame_src,
        )
        job_control.report_progress("encode done", phase="encode", current=1, total=1, unit="pass")
        logs.append(f"Output: {result_path} @ {F:g} fps (~{R_int / F:.3g}s)")
        success = True
        return OperationResult(
            ok=True, operation="speedchange", output_path=str(result_path),
            dry_run=False, command=summary, stdout="\n".join(logs), meta=plan,
        )
    except Exception as e:
        return OperationResult(
            ok=False, operation="speedchange", error=str(e),
            dry_run=False, command=summary, stdout="\n".join(logs), stderr=str(e),
        )
    finally:
        await cleanup(ws, keep_on_failure=not success)


register(OperationSpec(
    id="speedchange",
    summary="Unified Speed & Time — target length or multiplier, optional RIFE",
    description=(
        "Two chosen variables, never more: one of {Target Length | Speed "
        "Multiplier} plus an Output FPS (match source or custom `target_fps`). "
        "Optional RIFE generates intermediate frames (2,4,8,…); Snap locks the "
        "multiplier to the exact RIFE rate (zero waste), Free honors both chosen "
        "variables and `keep_extra` decides what to do with the overage "
        "(trim / encode-all @ raised fps / encode-all @ stretched duration). "
        "UI readout mirrors this math 1:1."
    ),
    params_model=SpeedChangeParams,
    handler=speedchange,
    tags=["speed", "time", "rife", "utility"],
))